# Golden fixture: statnet `ergm.multi`'s POOLED layer terms,
# `L(~term, c(~A, ~B))`, on the SAME frozen layers as twolayer_layer_terms.R.
#
# Regenerate from the package root (~20s):
#
#   Rscript test/fixtures/r/pooled_layer_terms.R > test/fixtures/pooled_layer_terms.toml
#
# WHAT IT PINS
#
# `L(~term, c(~A, ~B))` evaluates `term` on each listed layer and SUMS the
# statistics: one coefficient for the term across the layers. ERGMMulti.jl
# spells it `WithinLayer(term, [1, 2])` (or `WithinLayer(term, :)`). Before
# 0.2 that call was a MethodError, and only edges, mutual and triangle could
# be pooled.
#
# (i)  STATISTICS, directed layers: `summary()` of nineteen ergm terms pooled
#      over both layers -- structural, degree-based, nodal-attribute and
#      expanding (nodefactor, nodemix, idegree(0:2)) terms. Exact, 1e-10.
# (ii) A DYAD-DEPENDENT MPLE with pooled terms on the directed layers, as
#      shipped and refit to glm convergence (epsilon = 1e-14) on ergmMPLE's
#      own compressed design, exactly as in twolayer_layer_terms.R.
# (iii)/(iv) the same on the UNDIRECTED layers (kstar, gwdegree, degree,
#      concurrent, gwnsp, ...), with a pooled expanding nodefactor in the fit.
#
# THE DATA are generated by the same code and seed as the sibling scripts
# (the Julia testset asserts the edge lists agree with
# twolayer_layer_terms.toml), with two more deterministic vertex attributes:
# `g3` (three levels, for the expanding terms) and the numeric `x`.

suppressMessages({
  .libPaths(c(path.expand("~/R/library"), .libPaths()))
  library(network)
  library(ergm.multi)
})

seed <- 20260713
set.seed(seed)

# --- IDENTICAL to twolayer_ergm_multi.R / twolayer_layer_terms.R -------------
n <- 20
grp <- rep(c("a", "b"), length.out = n)
same <- outer(grp, grp, "==")
diag(same) <- FALSE
logistic <- function(x) 1 / (1 + exp(-x))

gen <- list(c(-1.5, 0.9), c(-2.0, 0.4))   # (edges, nodematch) per layer
mk <- function(th) {
  P <- logistic(th[1] + th[2] * same)
  A <- matrix(rbinom(n * n, 1, P), n, n)
  diag(A) <- 0
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- grp
  nw
}
nets <- lapply(gen, mk)
mats <- lapply(nets, function(nw) as.matrix(nw))

quiet <- function(expr) {
  out <- NULL
  invisible(capture.output(out <- eval.parent(substitute(expr)), type = "output"))
  out
}

# REPLAY of twolayer_layer_terms.R between its directed and its undirected
# layers: that script fits two MPLEs there, and `ergm()` consumes random
# numbers, so the undirected layers come out of the seed stream only after
# the same calls. The results are discarded; the Julia testset asserts that
# the undirected edge lists frozen here equal the sibling fixture's.
local({
  lnw <- Layer(list(A = nets[[1]], B = nets[[2]]))
  f <- lnw ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B) + L(~mutual, ~A)
  summary(lnw ~ L(~edges, ~A) + L(~edges, ~B) + L(~mutual, ~A) +
    L(~triangle, ~A) + L(~edges, ~A & B) + mutualL(Ls = list(~A, ~B)) +
    L(~gwesp(0.5, fixed = TRUE), ~A) + L(~ostar(2), ~B) +
    L(~nodematch("grp"), ~B) + L(~twopath, ~A))
  quiet(ergm(f, estimate = "MPLE"))
  quiet(ergmMPLE(f, output = "matrix"))
  nb <- 6
  cyc <- rbind(c(1, 2), c(2, 3), c(3, 4), c(4, 5), c(5, 6), c(6, 1))
  Ab <- matrix(0, nb, nb)
  Bb <- matrix(0, nb, nb)
  for (k in seq_len(nrow(cyc))) {
    Ab[cyc[k, 1], cyc[k, 2]] <- 1
    Bb[cyc[k, 2], cyc[k, 1]] <- 1
  }
  lnb <- Layer(list(A = network(Ab, directed = TRUE), B = network(Bb, directed = TRUE)))
  fb <- lnb ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B)
  summary(fb)
  suppressWarnings(quiet(ergm(fb, estimate = "MPLE")))
  invisible(NULL)
})

nu <- 12
grpu <- rep(c("a", "b"), length.out = nu)
sameu <- outer(grpu, grpu, "==")
diag(sameu) <- FALSE
genu <- list(c(-0.8, 0.7), c(-1.2, 0.5))   # (edges, nodematch) per layer
mku <- function(th) {
  P <- logistic(th[1] + th[2] * sameu)
  A <- matrix(0, nu, nu)
  for (i in 1:(nu - 1)) for (j in (i + 1):nu) {
    A[i, j] <- rbinom(1, 1, P[i, j])
    A[j, i] <- A[i, j]
  }
  nw <- network(A, directed = FALSE)
  nw %v% "grp" <- grpu
  nw
}
netsu <- lapply(genu, mku)
matsu <- lapply(netsu, function(nw) as.matrix(nw))
# ---------------------------------------------------------------------------

# Two more deterministic attributes, the same on both layers
g3 <- rep(c("a", "b", "c"), length.out = n)
x <- round(sin(1:n), 3)
g3u <- rep(c("a", "b", "c"), length.out = nu)
xu <- round(sin(1:nu), 3)
for (k in 1:2) {
  nets[[k]] %v% "g3" <- g3
  nets[[k]] %v% "x" <- x
  netsu[[k]] %v% "g3" <- g3u
  netsu[[k]] %v% "x" <- xu
}

tight <- glm.control(epsilon = 1e-14, maxit = 200)
exact_refit <- function(formula) {
  mm <- quiet(ergmMPLE(formula, output = "matrix"))
  g <- glm.fit(mm$predictor, mm$response, weights = mm$weights,
               family = binomial(), control = tight)
  list(coef = as.numeric(g$coefficients),
       se = sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE]))),
       universe = sum(mm$weights))
}
warned <- character(0)
fit_mple <- function(formula) withCallingHandlers(
  quiet(ergm(formula, estimate = "MPLE")),
  warning = function(w) {
    warned <<- c(warned, conditionMessage(w))
    invokeRestart("muffleWarning")
  })

# --- (i) directed statistics ------------------------------------------------
lnw <- Layer(list(A = nets[[1]], B = nets[[2]]))
AB <- c(~A, ~B)
stat_formula <- lnw ~ L(~edges, AB) + L(~mutual, AB) + L(~triangle, AB) +
  L(~gwesp(0.5, fixed = TRUE), AB) + L(~gwdsp(0.5, fixed = TRUE), AB) +
  L(~ostar(2), AB) + L(~istar(2), AB) + L(~twopath, AB) +
  L(~nodematch("grp"), AB) + L(~nodefactor("g3"), AB) + L(~nodemix("grp"), AB) +
  L(~nodecov("x"), AB) + L(~absdiff("x"), AB) +
  L(~idegree(0:2), AB) + L(~odegree(1:2), AB) +
  L(~gwidegree(0.3, fixed = TRUE), AB) + L(~gwodegree(0.3, fixed = TRUE), AB) +
  L(~meandeg, AB) + L(~density, AB)
stats <- summary(stat_formula)
julia_terms <- c("Edges()", "Mutual()", "Triangle()", "GWESP(0.5)", "GWDSP(0.5)",
                 "OStar(2)", "IStar(2)", "TwoPath()", "NodeMatch(:grp)",
                 "NodeFactor(:g3)", "NodeMix(:grp)", "NodeCov(:x)", "AbsDiff(:x)",
                 "IDegree(0:2)", "ODegree(1:2)", "GWIDegree(0.3)", "GWODegree(0.3)",
                 "MeanDeg()", "Density()")
# The pooled statistic is the SUM of the per-layer statistics: asserted here
# for the first eight (single-statistic) terms, so the claim is R's, not ours.
per_layer <- summary(lnw ~ L(~edges + mutual + triangle + gwesp(0.5, fixed = TRUE) +
                               gwdsp(0.5, fixed = TRUE) + ostar(2) + istar(2) + twopath, ~A) +
                       L(~edges + mutual + triangle + gwesp(0.5, fixed = TRUE) +
                           gwdsp(0.5, fixed = TRUE) + ostar(2) + istar(2) + twopath, ~B))
stopifnot(max(abs(stats[1:8] - (per_layer[1:8] + per_layer[9:16]))) < 1e-10)

# --- (ii) directed dyad-dependent MPLE with pooled terms ---------------------
mple_formula <- lnw ~ L(~edges, AB) + L(~mutual, AB) +
  L(~gwesp(0.5, fixed = TRUE), AB) + L(~nodematch("grp"), AB) + L(~edges, ~A & B)
fit <- fit_mple(mple_formula)
mple_coef <- as.numeric(coef(fit))
mple_se <- as.numeric(sqrt(diag(vcov(fit))))
ex <- exact_refit(mple_formula)
stopifnot(ex$universe == 2 * n * (n - 1))

# --- (iii) undirected statistics ---------------------------------------------
lnu <- Layer(list(A = netsu[[1]], B = netsu[[2]]))
und_stat_formula <- lnu ~ L(~edges, AB) + L(~triangle, AB) + L(~kstar(2), AB) +
  L(~gwesp(0.5, fixed = TRUE), AB) + L(~gwdsp(0.5, fixed = TRUE), AB) +
  L(~gwnsp(0.5, fixed = TRUE), AB) + L(~gwdegree(0.3, fixed = TRUE), AB) +
  L(~degree(0:2), AB) + L(~concurrent, AB) + L(~nodematch("grp"), AB) +
  L(~nodefactor("g3"), AB) + L(~nodemix("g3"), AB) + L(~nodecov("x"), AB) +
  L(~absdiff("x"), AB) + L(~degrange(2, 4), AB)
und_stats <- summary(und_stat_formula)
und_julia_terms <- c("Edges()", "Triangle()", "Kstar(2)", "GWESP(0.5)", "GWDSP(0.5)",
                     "GWNSP(0.5)", "GWDegree(0.3)", "Degree(0:2)", "Concurrent()",
                     "NodeMatch(:grp)", "NodeFactor(:g3)", "NodeMix(:g3)",
                     "NodeCov(:x)", "AbsDiff(:x)", "DegRange(2, 4)")

# --- (iv) undirected dyad-dependent MPLE with pooled terms -------------------
und_mple_formula <- lnu ~ L(~edges, AB) + L(~gwesp(0.5, fixed = TRUE), AB) +
  L(~nodefactor("g3"), AB) + L(~gwdegree(0.3, fixed = TRUE), ~B) + L(~edges, ~A & B)
und_fit <- fit_mple(und_mple_formula)
und_mple_coef <- as.numeric(coef(und_fit))
und_mple_se <- as.numeric(sqrt(diag(vcov(und_fit))))
und_ex <- exact_refit(und_mple_formula)
stopifnot(und_ex$universe == 2 * nu * (nu - 1) / 2)
stopifnot(length(warned) == 0)

num <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
strs <- function(x) paste(sprintf('"%s"', x), collapse = ", ")
elist <- function(sel) paste(sapply(mats, function(A) {
  e <- which(A == 1, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")
ulist <- function(sel) paste(sapply(matsu, function(A) {
  e <- which(A == 1 & upper.tri(A), arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")
# The as-shipped tolerance: 20x the measured glm slack d, rounded up to a
# power of ten. The 1e-12 floor on d leaves room for the last digits of
# either optimizer when R's glm happens to stop on the optimum itself; there
# is no floor on the tolerance, so it is always set by the measurement.
tol_from <- function(d) sprintf("%.1g", 10^ceiling(log10(20 * max(d, 1e-12))))
d_coef <- max(abs(mple_coef - ex$coef)); d_se <- max(abs(mple_se - ex$se))
ud_coef <- max(abs(und_mple_coef - und_ex$coef)); ud_se <- max(abs(und_mple_se - und_ex$se))

cat('name = "pooled_layer_terms"\n\n')
cat("[provenance]\n")
cat(sprintf('r_version = "%s"\n', as.character(getRversion())))
cat(sprintf('ergm_multi_version = "%s"\n', as.character(packageVersion("ergm.multi"))))
cat(sprintf('ergm_version = "%s"\n', as.character(packageVersion("ergm"))))
cat(sprintf('network_version = "%s"\n', as.character(packageVersion("network"))))
cat(sprintf("seed = %d\n", seed))
cat('script = "test/fixtures/r/pooled_layer_terms.R"\n')
cat(sprintf('date = "%s"\n', format(Sys.Date())))
cat('dataset = "the SAME directed 20-actor and undirected 12-actor layer pairs as twolayer_layer_terms.toml (identical generating code and seed), plus the deterministic vertex attributes g3 = rep(a,b,c) and x = round(sin(1:n), 3) on both layers; frozen below as edge lists"\n')
cat('statistics = "summary() of L(~term, c(~A, ~B)) for nineteen ergm terms on the directed layers (und_: fifteen on the undirected layers); the pooled statistic is the sum of the per-layer statistics (asserted in the script)"\n')
cat('model_mple = "ergm(lnw ~ L(~edges, c(~A,~B)) + L(~mutual, c(~A,~B)) + L(~gwesp(0.5,fixed=TRUE), c(~A,~B)) + L(~nodematch(\\"grp\\"), c(~A,~B)) + L(~edges, ~A&B), estimate = \\"MPLE\\")"\n')
cat('und_model_mple = "ergm(lnu ~ L(~edges, c(~A,~B)) + L(~gwesp(0.5,fixed=TRUE), c(~A,~B)) + L(~nodefactor(\\"g3\\"), c(~A,~B)) + L(~gwdegree(0.3,fixed=TRUE), ~B) + L(~edges, ~A&B), estimate = \\"MPLE\\")"\n')
cat('exact_estimator = "the same pseudo-likelihood refit with glm at epsilon = 1e-14 on ergmMPLE(output = \\"matrix\\")\'s own compressed design, since ergm stops its MPLE glm at the default 1e-8"\n')
cat('r_warnings = "none (stopifnot in the script)"\n')
cat("\n")

cat("[tolerance]\n")
cat("# The statistics are exact counts (and geometrically weighted decimals):\n")
cat("# both sides compute them in closed form. DO NOT LOOSEN.\n")
cat("statistics = 1e-10\n")
cat("und_statistics = 1e-10\n")
cat("# The MPLE is a deterministic function of the change-statistic design; the\n")
cat("# exact refit (glm epsilon 1e-14 on R's own design) is the assertion with\n")
cat("# teeth. DO NOT LOOSEN.\n")
cat("exact_mple_coefficients = 1e-6\n")
cat("exact_mple_std_errors = 1e-6\n")
cat("und_exact_mple_coefficients = 1e-6\n")
cat("und_exact_mple_std_errors = 1e-6\n")
cat("# As shipped: 20x the measured glm slack (mple_vs_exact_* below), rounded\n")
cat("# up to a power of ten (no floor).\n")
cat(sprintf("mple_coefficients = %s\n", tol_from(d_coef)))
cat(sprintf("mple_std_errors = %s\n", tol_from(d_se)))
cat(sprintf("und_mple_coefficients = %s\n", tol_from(ud_coef)))
cat(sprintf("und_mple_std_errors = %s\n", tol_from(ud_se)))
cat("\n")

cat("[values]\n")
cat(sprintf("n_actors = %d\n", n))
cat(sprintf("grp = [%s]\n", strs(grp)))
cat(sprintf("g3 = [%s]\n", strs(g3)))
cat(sprintf("x = [%s]\n", num(x)))
cat(sprintf("layer_src = [%s]\n", elist(1)))
cat(sprintf("layer_dst = [%s]\n", elist(2)))
cat("\n# --- (i) directed statistics --------------------------------------------\n")
cat(sprintf("stat_names = [%s]\n", strs(names(stats))))
cat(sprintf("stat_julia_terms = [%s]\n", strs(julia_terms)))
cat(sprintf("statistics = [%s]\n", num(as.numeric(stats))))
cat("\n# --- (ii) directed MPLE --------------------------------------------------\n")
cat(sprintf("mple_term_names = [%s]\n", strs(names(coef(fit)))))
cat('mple_julia_terms = ["WithinLayer(Edges(), [1, 2])", "WithinLayer(Mutual(), [1, 2])", "WithinLayer(GWESP(0.5), [1, 2])", "WithinLayer(NodeMatch(:grp), [1, 2])", "InterlayerDependence(1, 2)"]\n')
cat(sprintf("mple_coefficients = [%s]\n", num(mple_coef)))
cat(sprintf("mple_std_errors = [%s]\n", num(mple_se)))
cat(sprintf("exact_mple_coefficients = [%s]\n", num(ex$coef)))
cat(sprintf("exact_mple_std_errors = [%s]\n", num(ex$se)))
cat(sprintf("mple_dyad_universe = %d\n", as.integer(ex$universe)))
cat(sprintf("mple_vs_exact_coef = %.17g\n", d_coef))
cat(sprintf("mple_vs_exact_se = %.17g\n", d_se))
cat("\n# --- (iii) undirected statistics ----------------------------------------\n")
cat(sprintf("und_n_actors = %d\n", nu))
cat(sprintf("und_grp = [%s]\n", strs(grpu)))
cat(sprintf("und_g3 = [%s]\n", strs(g3u)))
cat(sprintf("und_x = [%s]\n", num(xu)))
cat(sprintf("und_layer_src = [%s]\n", ulist(1)))
cat(sprintf("und_layer_dst = [%s]\n", ulist(2)))
cat(sprintf("und_stat_names = [%s]\n", strs(names(und_stats))))
cat(sprintf("und_stat_julia_terms = [%s]\n", strs(und_julia_terms)))
cat(sprintf("und_statistics = [%s]\n", num(as.numeric(und_stats))))
cat("\n# --- (iv) undirected MPLE -----------------------------------------------\n")
cat(sprintf("und_mple_term_names = [%s]\n", strs(names(coef(und_fit)))))
cat('und_mple_julia_terms = ["WithinLayer(Edges(), [1, 2])", "WithinLayer(GWESP(0.5), [1, 2])", "WithinLayer(NodeFactor(:g3), [1, 2])", "WithinLayer(GWDegree(0.3), 2)", "InterlayerDependence(1, 2)"]\n')
cat(sprintf("und_mple_coefficients = [%s]\n", num(und_mple_coef)))
cat(sprintf("und_mple_std_errors = [%s]\n", num(und_mple_se)))
cat(sprintf("und_exact_mple_coefficients = [%s]\n", num(und_ex$coef)))
cat(sprintf("und_exact_mple_std_errors = [%s]\n", num(und_ex$se)))
cat(sprintf("und_mple_dyad_universe = %d\n", as.integer(und_ex$universe)))
cat(sprintf("und_mple_vs_exact_coef = %.17g\n", ud_coef))
cat(sprintf("und_mple_vs_exact_se = %.17g\n", ud_se))
