# Golden fixture: statnet `ergm.multi`'s LAYER terms on the SAME two frozen
# layers as twolayer_ergm_multi.R -- every ERGMMulti.jl term with an
# ergm.multi counterpart, and a DYAD-DEPENDENT MPLE.
#
# Regenerate from the package root (~20s):
#
#   Rscript test/fixtures/r/twolayer_layer_terms.R > test/fixtures/twolayer_layer_terms.toml
#
# THE DATA
#
# The two directed 20-actor layers are generated by the SAME code, from the
# SAME seed (20260713), as test/fixtures/r/twolayer_ergm_multi.R, so the two
# fixtures describe one network (the Julia testset asserts the edge lists
# agree). Here they are wrapped as ergm.multi's multilayer construct,
#
#   lnw <- Layer(list(A = net1, B = net2))
#
# which is the block-diagonal network with layer-membership attributes that
# ERGMMulti.jl's `MultilayerNetwork` mirrors. `L(~term, ~A)` is a term
# evaluated within layer A (ERGMMulti.jl: `WithinLayer(term, 1)`, or the
# dedicated `LayerEdges(1)`, `LayerMutual(1)`, `LayerTriangle(1)`); `L(~edges,
# ~A&B)` counts the ORDERED dyads tied in both layers (`InterlayerDependence(1,
# 2)`); `mutualL(Ls = list(~A, ~B))` counts the ORDERED dyads (i, j) with i->j
# in A and j->i in B (`MultiplexMutual(1, 2)`). Both cross-layer counts were
# checked on a 4-actor example where ordered and unordered counting differ (3
# vs 2): ergm.multi counts ordered dyads, and so does ERGMMulti.jl.
#
# (i) STATISTICS. `summary()` of ten layer terms, frozen exactly. Integers, or
#     the gwesp decay's decimals, so the tolerance is 1e-10: a disagreement is
#     a wrong statistic, not rounding.
#
# (ii) A DYAD-DEPENDENT MPLE.
#
#   ergm(lnw ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A&B) + L(~mutual, ~A),
#        estimate = "MPLE")
#
# The first fixture's model is dyad-independent, so it pins the dyad universe
# and the logistic kernel but not the CHANGE STATISTICS of a term that reads
# other dyads. `L(~edges, ~A&B)` reads the other layer's dyad and `L(~mutual,
# ~A)` the reverse dyad, so this fit is what licenses ERGMMulti.jl's
# `InterlayerDependence` and `LayerMutual` change statistics against R's: the
# MPLE is a deterministic function of the change-statistic design (no Monte
# Carlo on either side), so the two packages must agree to optimizer precision.
# As in the sibling fixture, ergm's `glm` stops at epsilon = 1e-8; the same
# pseudo-likelihood is refit at 1e-14 from `ergmMPLE(..., output = "matrix")`
# (R's OWN compressed design: response / predictor / weights), the distance
# between the two is measured (`mple_vs_exact_*`), and the as-shipped
# tolerances are set from the measurement. The exact refit is the assertion
# with teeth.
#
# (iii) A BOUNDARY STATISTIC: DOCUMENTED DIVERGENCE. A 6-actor design (layer A
#     the directed 6-cycle, layer B the reversed cycle) on which no dyad is
#     tied in both layers, so `L(~edges, ~A&B)` sits at its smallest
#     attainable value and the MPLE has no finite maximum. R ergm's default
#     `drop=TRUE` fixes such a coefficient at -Inf for one-mode terms, but
#     ergm.multi's layer operator does NOT propagate the statistic's
#     attainable range to `ergm.checkextreme.model`: `ergm(..., estimate =
#     "MPLE")` warns "The MPLE does not exist!" (mple.existence) and returns a
#     FINITE ~-17.6 with a standard error in the thousands for that term, the
#     finite coefficients being logit(6/18) exactly (the MPLE on the 24 dyads
#     of each layer the dropped column does not touch). ERGMMulti.jl applies
#     the drop (-Inf, SE 0) and must agree with R on the finite coefficients;
#     R's finite value for the boundary term is frozen so the divergence is a
#     pinned fact, not a claim.
#
# (iv) UNDIRECTED LAYERS. Sections (i)-(iii) are directed. The undirected
#     branch of ERGMMulti.jl is a different code path -- the dyad universe is
#     the unordered pairs i < j (nobs = L * n * (n - 1) / 2), `L(~edges,
#     ~A&B)` counts UNORDERED co-occurrences, `triangle`/`gwesp`/`kstar`/
#     `gwdegree` take their undirected forms -- so it gets its own pin: two
#     undirected 12-actor layers drawn from the SAME seed stream right after
#     the directed ones (frozen as edge lists), the summary() of the
#     undirected layer terms, and the dyad-dependent MPLE
#
#   ergm(lnu ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A&B) + L(~triangle, ~A),
#        estimate = "MPLE")
#
#     as shipped plus the same exact glm refit on ergmMPLE's compressed
#     design (weights summing to 2 * 12 * 11 / 2 = 132, asserted and frozen).

suppressMessages({
  .libPaths(c(path.expand("~/R/library"), .libPaths()))
  library(network)
  library(ergm.multi)
})

seed <- 20260713
set.seed(seed)

# --- IDENTICAL to twolayer_ergm_multi.R: same draws, same layers ------------
n <- 20
grp <- rep(c("a", "b"), length.out = n)
same <- outer(grp, grp, "==")
diag(same) <- FALSE
logistic <- function(x) 1 / (1 + exp(-x))

gen <- list(c(-1.5, 0.9), c(-2.0, 0.4))   # (edges, nodematch) per layer
mk <- function(th) {
  P <- logistic(th[1] + th[2] * same)
  A <- matrix(rbinom(n * n, 1, P), n, n)
  diag(A) <- 0
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- grp
  nw
}
nets <- lapply(gen, mk)
mats <- lapply(nets, function(nw) as.matrix(nw))
# ---------------------------------------------------------------------------

quiet <- function(expr) {
  out <- NULL
  invisible(capture.output(out <- eval.parent(substitute(expr)), type = "output"))
  out
}

lnw <- Layer(list(A = nets[[1]], B = nets[[2]]))

# --- (i) the statistics ------------------------------------------------------
stat_formula <- lnw ~ L(~edges, ~A) + L(~edges, ~B) + L(~mutual, ~A) +
  L(~triangle, ~A) + L(~edges, ~A & B) + mutualL(Ls = list(~A, ~B)) +
  L(~gwesp(0.5, fixed = TRUE), ~A) + L(~ostar(2), ~B) +
  L(~nodematch("grp"), ~B) + L(~twopath, ~A)
stats <- summary(stat_formula)

# The Julia terms, in the same order, for the reader and the testset
julia_terms <- c("LayerEdges(1)", "LayerEdges(2)", "LayerMutual(1)",
                 "LayerTriangle(1)", "InterlayerDependence(1, 2)",
                 "MultiplexMutual(1, 2)", "WithinLayer(GWESP(0.5), 1)",
                 "WithinLayer(OStar(2), 2)", "WithinLayer(NodeMatch(:grp), 2)",
                 "WithinLayer(TwoPath(), 1)")

# --- (ii) the dyad-dependent MPLE --------------------------------------------
mple_formula <- lnw ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B) +
  L(~mutual, ~A)
fit <- quiet(ergm(mple_formula, estimate = "MPLE"))
mple_coef <- as.numeric(coef(fit))
mple_se <- sqrt(diag(vcov(fit)))

# The same pseudo-likelihood taken to convergence, on R's OWN compressed
# design: `ergmMPLE(output = "matrix")` returns the unique change-statistic
# rows, the tie indicator and the dyad multiplicity (weights). The weights
# must sum to the within-layer dyad universe, 2 * 20 * 19 = 760 -- asserted
# below and frozen, so a design that leaked the block-diagonal constraint's
# cross-layer dyads could not go unnoticed.
mm <- quiet(ergmMPLE(mple_formula, output = "matrix"))
n_universe <- sum(mm$weights)
stopifnot(n_universe == 2 * n * (n - 1))
tight <- glm.control(epsilon = 1e-14, maxit = 200)
g <- glm.fit(mm$predictor, mm$response, weights = mm$weights,
             family = binomial(), control = tight)
exact_coef <- as.numeric(g$coefficients)
exact_se <- sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE])))
mple_vs_exact_coef <- max(abs(mple_coef - exact_coef))
mple_vs_exact_se <- max(abs(as.numeric(mple_se) - exact_se))

# --- (iii) the boundary design: ergm.multi does not drop -----------------
nb <- 6
cyc <- rbind(c(1, 2), c(2, 3), c(3, 4), c(4, 5), c(5, 6), c(6, 1))
Ab <- matrix(0, nb, nb)
Bb <- matrix(0, nb, nb)
for (k in seq_len(nrow(cyc))) {
  Ab[cyc[k, 1], cyc[k, 2]] <- 1
  Bb[cyc[k, 2], cyc[k, 1]] <- 1
}
lnb <- Layer(list(A = network(Ab, directed = TRUE), B = network(Bb, directed = TRUE)))
boundary_formula <- lnb ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B)
boundary_stats <- summary(boundary_formula)
stopifnot(boundary_stats[3] == 0)
boundary_warned <- FALSE
bfit <- withCallingHandlers(
  quiet(ergm(boundary_formula, estimate = "MPLE")),
  warning = function(w) {
    if (grepl("MPLE does not exist", conditionMessage(w))) boundary_warned <<- TRUE
    invokeRestart("muffleWarning")
  })
boundary_coef <- as.numeric(coef(bfit))
boundary_se <- sqrt(diag(vcov(bfit)))
stopifnot(boundary_warned, all(is.finite(boundary_coef)))

# --- (iv) undirected layers: the same seed stream, continued ----------------
nu <- 12
grpu <- rep(c("a", "b"), length.out = nu)
sameu <- outer(grpu, grpu, "==")
diag(sameu) <- FALSE
genu <- list(c(-0.8, 0.7), c(-1.2, 0.5))   # (edges, nodematch) per layer
mku <- function(th) {
  P <- logistic(th[1] + th[2] * sameu)
  A <- matrix(0, nu, nu)
  for (i in 1:(nu - 1)) for (j in (i + 1):nu) {
    A[i, j] <- rbinom(1, 1, P[i, j])
    A[j, i] <- A[i, j]
  }
  nw <- network(A, directed = FALSE)
  nw %v% "grp" <- grpu
  nw
}
netsu <- lapply(genu, mku)
matsu <- lapply(netsu, function(nw) as.matrix(nw))
lnu <- Layer(list(A = netsu[[1]], B = netsu[[2]]))

und_stat_formula <- lnu ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B) +
  L(~triangle, ~A) + L(~gwesp(0.5, fixed = TRUE), ~A) +
  L(~nodematch("grp"), ~B) + L(~kstar(2), ~B) + L(~gwdegree(0.3, fixed = TRUE), ~B)
und_stats <- summary(und_stat_formula)
und_julia_terms <- c("LayerEdges(1)", "LayerEdges(2)", "InterlayerDependence(1, 2)",
                     "LayerTriangle(1)", "WithinLayer(GWESP(0.5), 1)",
                     "WithinLayer(NodeMatch(:grp), 2)", "WithinLayer(Kstar(2), 2)",
                     "WithinLayer(GWDegree(0.3), 2)")

und_mple_formula <- lnu ~ L(~edges, ~A) + L(~edges, ~B) + L(~edges, ~A & B) +
  L(~triangle, ~A)
und_fit <- quiet(ergm(und_mple_formula, estimate = "MPLE"))
und_mple_coef <- as.numeric(coef(und_fit))
und_mple_se <- sqrt(diag(vcov(und_fit)))
und_mm <- quiet(ergmMPLE(und_mple_formula, output = "matrix"))
und_n_universe <- sum(und_mm$weights)
stopifnot(und_n_universe == 2 * nu * (nu - 1) / 2)
und_g <- glm.fit(und_mm$predictor, und_mm$response, weights = und_mm$weights,
                 family = binomial(), control = tight)
und_exact_coef <- as.numeric(und_g$coefficients)
und_exact_se <- sqrt(diag(chol2inv(und_g$qr$qr[1:und_g$rank, 1:und_g$rank, drop = FALSE])))
und_mple_vs_exact_coef <- max(abs(und_mple_coef - und_exact_coef))
und_mple_vs_exact_se <- max(abs(as.numeric(und_mple_se) - und_exact_se))

num <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
strs <- function(x) paste(sprintf('"%s"', x), collapse = ", ")
elist <- function(sel, ms = mats) paste(sapply(ms, function(A) {
  e <- which(A == 1, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")
# undirected layers: each unordered pair once, as i < j
ulist <- function(sel) paste(sapply(matsu, function(A) {
  e <- which(A == 1 & upper.tri(A), arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")
tol_from <- function(d) sprintf("%.1g", max(1e-6, 10^ceiling(log10(20 * max(d, 1e-12)))))

cat('name = "twolayer_layer_terms"\n\n')

cat("[provenance]\n")
cat(sprintf('r_version = "%s"\n', as.character(getRversion())))
cat(sprintf('ergm_multi_version = "%s"\n', as.character(packageVersion("ergm.multi"))))
cat(sprintf('ergm_version = "%s"\n', as.character(packageVersion("ergm"))))
cat(sprintf('network_version = "%s"\n', as.character(packageVersion("network"))))
cat(sprintf("seed = %d\n", seed))
cat('script = "test/fixtures/r/twolayer_layer_terms.R"\n')
cat(sprintf('date = "%s"\n', format(Sys.Date())))
cat('dataset = "the SAME two directed 20-actor layers as twolayer_ergm_multi.toml (identical generating code and seed), wrapped as ergm.multi Layer(list(A = net1, B = net2)); frozen below as edge lists"\n')
cat('statistics = "summary(lnw ~ L(~edges,~A) + L(~edges,~B) + L(~mutual,~A) + L(~triangle,~A) + L(~edges,~A&B) + mutualL(Ls=list(~A,~B)) + L(~gwesp(0.5,fixed=TRUE),~A) + L(~ostar(2),~B) + L(~nodematch(\\"grp\\"),~B) + L(~twopath,~A))"\n')
cat('model_mple = "ergm(lnw ~ L(~edges,~A) + L(~edges,~B) + L(~edges,~A&B) + L(~mutual,~A), estimate = \\"MPLE\\") -- DYAD-DEPENDENT (the cross-layer and mutual terms read other dyads), so the MPLE is not the MLE on either side; it is the same deterministic function of the change statistics"\n')
cat('exact_estimator = "the same pseudo-likelihood refit with glm at epsilon = 1e-14 on ergmMPLE(output = \\"matrix\\")\'s own compressed design (response / predictor / weights), since ergm stops its MPLE glm at the default 1e-8"\n')
cat('model_boundary = "ergm(lnb ~ L(~edges,~A) + L(~edges,~B) + L(~edges,~A&B), estimate = \\"MPLE\\") on the 6-actor cycle/reversed-cycle design where L(A&B)~edges is 0 (its smallest attainable value): ergm.multi warns \\"The MPLE does not exist!\\" and returns a FINITE coefficient for the boundary term (it does not apply ergm\'s drop=TRUE to layer terms); ERGMMulti.jl fixes it at -Inf and agrees on the finite coefficients"\n')
cat('und_dataset = "two UNDIRECTED 12-actor layers drawn from the same seed stream immediately after the directed ones (Bernoulli on the unordered pairs i < j at logistic(edges + nodematch * same-grp)), wrapped as Layer(list(A = netA, B = netB)); frozen below as edge lists with i < j"\n')
cat('und_statistics = "summary(lnu ~ L(~edges,~A) + L(~edges,~B) + L(~edges,~A&B) + L(~triangle,~A) + L(~gwesp(0.5,fixed=TRUE),~A) + L(~nodematch(\\"grp\\"),~B) + L(~kstar(2),~B) + L(~gwdegree(0.3,fixed=TRUE),~B))"\n')
cat('und_model_mple = "ergm(lnu ~ L(~edges,~A) + L(~edges,~B) + L(~edges,~A&B) + L(~triangle,~A), estimate = \\"MPLE\\") -- DYAD-DEPENDENT, on the unordered within-layer dyads; as shipped and refit exactly (glm epsilon 1e-14) on ergmMPLE(output = \\"matrix\\")\'s design, whose weights sum to 2 * 12 * 11 / 2 = 132"\n')
cat("\n")

cat("[tolerance]\n")
cat("# (i) The statistics are exact counts (and the gwesp decay's decimals):\n")
cat("# both sides compute them in closed form. Any disagreement is a wrong\n")
cat("# statistic, not rounding. DO NOT LOOSEN IT.\n")
cat("statistics = 1e-10\n")
cat("#\n")
cat("# (ii) The MPLE is a deterministic function of the change-statistic design:\n")
cat("# no Monte Carlo on either side, so two correct implementations differ only\n")
cat("# in where their optimizers stop. `exact_mple_*` is R's own design refit at\n")
cat("# epsilon = 1e-14, and THAT is the assertion with teeth: 1e-6, ~1e-5 of the\n")
cat("# smallest standard error. If it fails, a change statistic of the\n")
cat("# cross-layer or mutual term (or the dyad universe) is wrong. DO NOT LOOSEN IT.\n")
cat("exact_mple_coefficients = 1e-6\n")
cat("exact_mple_std_errors = 1e-6\n")
cat("#\n")
cat("# Against ergm.multi AS SHIPPED the tolerance must also absorb ergm's own glm\n")
cat("# slack, which `mple_vs_exact_*` in [values] measures; the tolerance is 20x the\n")
cat("# measurement rounded up to a power of ten (floor 1e-6), not hand-chosen.\n")
cat(sprintf("mple_coefficients = %s\n", tol_from(mple_vs_exact_coef)))
cat(sprintf("mple_std_errors = %s\n", tol_from(mple_vs_exact_se)))
cat("#\n")
cat("# (iii) The boundary design's FINITE coefficients are logit(6/18) in closed\n")
cat("# form on both sides (R's glm at epsilon = 1e-8 lands on them to ~1e-9);\n")
cat("# the boundary term itself is where the two packages DIVERGE by design and\n")
cat("# is asserted as -Inf here against R's finite value, not compared.\n")
cat("boundary_finite_coefficients = 1e-6\n")
cat("#\n")
cat("# (iv) The undirected layers: the same three kinds of tolerance as (i)/(ii),\n")
cat("# the as-shipped ones again 20x the measured glm slack.\n")
cat("und_statistics = 1e-10\n")
cat("und_exact_mple_coefficients = 1e-6\n")
cat("und_exact_mple_std_errors = 1e-6\n")
cat(sprintf("und_mple_coefficients = %s\n", tol_from(und_mple_vs_exact_coef)))
cat(sprintf("und_mple_std_errors = %s\n", tol_from(und_mple_vs_exact_se)))
cat("\n")

cat("[values]\n")
cat("# --- the two layers, frozen (identical to twolayer_ergm_multi.toml) ------\n")
cat(sprintf("n_actors = %d\n", n))
cat("n_layers = 2\n")
cat("directed = true\n")
cat(sprintf("grp = [%s]\n", strs(grp)))
cat(sprintf("edge_counts = [%s]\n", paste(sapply(mats, sum), collapse = ", ")))
cat(sprintf("layer_src = [%s]\n", elist(1)))
cat(sprintf("layer_dst = [%s]\n", elist(2)))
cat("\n# --- (i) the statistics: R's names, the Julia terms, the values ----------\n")
cat(sprintf("stat_names = [%s]\n", strs(names(stats))))
cat(sprintf("stat_julia_terms = [%s]\n", strs(julia_terms)))
cat(sprintf("statistics = [%s]\n", num(as.numeric(stats))))
cat("\n# --- (ii) the dyad-dependent MPLE ---------------------------------------\n")
cat(sprintf("mple_term_names = [%s]\n", strs(names(coef(fit)))))
cat('mple_julia_terms = ["LayerEdges(1)", "LayerEdges(2)", "InterlayerDependence(1, 2)", "LayerMutual(1)"]\n')
cat(sprintf("mple_coefficients = [%s]\n", num(mple_coef)))
cat(sprintf("mple_std_errors = [%s]\n", num(as.numeric(mple_se))))
cat("# ...and the same pseudo-likelihood taken to convergence on R's own\n")
cat("# compressed design. This is what ERGMMulti.jl is actually held to.\n")
cat(sprintf("exact_mple_coefficients = [%s]\n", num(exact_coef)))
cat(sprintf("exact_mple_std_errors = [%s]\n", num(exact_se)))
cat("# The within-layer dyad universe ergmMPLE's weights sum to: 2 * 20 * 19.\n")
cat(sprintf("mple_dyad_universe = %d\n", as.integer(n_universe)))
cat(sprintf("mple_design_rows = %d\n", nrow(mm$predictor)))
cat("# How far ergm.multi AS SHIPPED sits from that exact optimum (its glm stops\n")
cat("# at the default epsilon = 1e-8).\n")
cat(sprintf("mple_vs_exact_coef = %.17g\n", mple_vs_exact_coef))
cat(sprintf("mple_vs_exact_se = %.17g\n", mple_vs_exact_se))
cat("\n# --- (iii) the boundary design: ergm.multi warns but does not drop --------\n")
cat(sprintf("boundary_n_actors = %d\n", nb))
cat(sprintf("boundary_layer_a_src = [%s]\n", paste(cyc[, 1], collapse = ", ")))
cat(sprintf("boundary_layer_a_dst = [%s]\n", paste(cyc[, 2], collapse = ", ")))
cat("# layer B is the reversed cycle (dst -> src), so no ordered dyad is tied in both\n")
cat(sprintf("boundary_stat_names = [%s]\n", strs(names(boundary_stats))))
cat('boundary_julia_terms = ["LayerEdges(1)", "LayerEdges(2)", "InterlayerDependence(1, 2)"]\n')
cat(sprintf("boundary_statistics = [%s]\n", num(as.numeric(boundary_stats))))
cat(sprintf("boundary_mple_exists_warning = %s\n", if (boundary_warned) "true" else "false"))
cat("# R's coefficients AS SHIPPED: the first two are logit(6/18); the third is\n")
cat("# finite (ergm.multi does not drop) with a standard error in the thousands.\n")
cat("# ERGMMulti.jl returns -Inf with standard error 0 for the third.\n")
cat(sprintf("boundary_r_coefficients = [%s]\n", num(boundary_coef)))
cat(sprintf("boundary_r_std_errors = [%s]\n", num(as.numeric(boundary_se))))
cat(sprintf("boundary_finite_coefficients = [%s]\n", num(boundary_coef[1:2])))
cat("\n# --- (iv) the undirected layers ---------------------------------------------\n")
cat(sprintf("und_n_actors = %d\n", nu))
cat("und_n_layers = 2\n")
cat("und_directed = false\n")
cat(sprintf("und_grp = [%s]\n", strs(grpu)))
cat(sprintf("und_edge_counts = [%s]\n", paste(sapply(matsu, function(A) sum(A[upper.tri(A)])), collapse = ", ")))
cat(sprintf("und_layer_src = [%s]\n", ulist(1)))
cat(sprintf("und_layer_dst = [%s]\n", ulist(2)))
cat(sprintf("und_stat_names = [%s]\n", strs(names(und_stats))))
cat(sprintf("und_stat_julia_terms = [%s]\n", strs(und_julia_terms)))
cat(sprintf("und_statistics = [%s]\n", num(as.numeric(und_stats))))
cat(sprintf("und_mple_term_names = [%s]\n", strs(names(coef(und_fit)))))
cat('und_mple_julia_terms = ["LayerEdges(1)", "LayerEdges(2)", "InterlayerDependence(1, 2)", "LayerTriangle(1)"]\n')
cat(sprintf("und_mple_coefficients = [%s]\n", num(und_mple_coef)))
cat(sprintf("und_mple_std_errors = [%s]\n", num(as.numeric(und_mple_se))))
cat(sprintf("und_exact_mple_coefficients = [%s]\n", num(und_exact_coef)))
cat(sprintf("und_exact_mple_std_errors = [%s]\n", num(und_exact_se)))
cat("# The UNORDERED within-layer dyad universe ergmMPLE's weights sum to: 2 * 12 * 11 / 2.\n")
cat(sprintf("und_mple_dyad_universe = %d\n", as.integer(und_n_universe)))
cat(sprintf("und_mple_design_rows = %d\n", nrow(und_mm$predictor)))
cat(sprintf("und_mple_vs_exact_coef = %.17g\n", und_mple_vs_exact_coef))
cat(sprintf("und_mple_vs_exact_se = %.17g\n", und_mple_vs_exact_se))
