# Golden fixture: statnet `ergm.multi` on a simulated two-network multilayer,
# with and without OFFSETS.
#
# Regenerate from the package root (~20s):
#
#   Rscript test/fixtures/r/twolayer_ergm_multi.R > test/fixtures/twolayer_ergm_multi.toml
#
# THE MODEL
#
#   Networks(list(net1, net2)) ~ N(~edges + nodematch("grp"), ~factor(.NetworkID) - 1)
#
# `N(formula, lm)` is ergm.multi's per-network term: the `~factor(.NetworkID) - 1`
# linear model gives each network its OWN coefficient for each term in `formula`,
# so the fit has four parameters -- edges and nodematch, per layer. That is
# exactly the dyad universe ERGMMulti.jl's MPLE works over, (layer, i, j), and
# exactly the model
#
#   [LayerEdges(1), LayerEdges(2),
#    WithinLayer(NodeMatch(:grp), 1), WithinLayer(NodeMatch(:grp), 2)]
#
# expresses in Julia. The terms are DYAD-INDEPENDENT on purpose: the likelihood
# factorizes over (layer, i, j), so ergm's MPLE is the exact MLE and ERGMMulti.jl's
# MPLE is the same exact MLE. No Monte Carlo on either side, and the comparison
# can be asserted at optimizer precision rather than hand-waved.
#
# OFFSETS -- the second half, and the reason ergm.multi is worth validating
# against at all rather than just two separate ergm() calls
#
# ERGMMulti.jl takes `offsets::Dict{Int,Float64}`: named parameters held FIXED at
# a stated value, contributing to the linear predictor but not estimated. That is
# statnet's `offset()` mechanism, and it is easy to get subtly wrong -- an offset
# that is dropped from the linear predictor instead of merely from the parameter
# vector produces a fit that looks fine and is wrong. So the fixture freezes a
# SECOND fit,
#
#   ~ N(~edges, ~factor(.NetworkID) - 1)
#     + offset(N(~nodematch("grp"), ~factor(.NetworkID) - 1)),  offset.coef = (0.75, 0.40)
#
# in which the two nodematch coefficients are pinned and only the two edges
# coefficients are free. If ERGMMulti.jl's offsets were ignored rather than
# applied, its edges coefficients would come back at the values from a model with
# NO nodematch term at all -- so the fixture freezes that null-comparison fit too
# (`no_nodematch_coefficients`), and the Julia testset asserts the offset fit is
# NOT equal to it. A test that only checked "the offset fit matches R" could pass
# while both sides did nothing; this one cannot.
#
# The panel is generated by explicit Bernoulli draws from the dyad-independent
# model being fitted (three lines of `rbinom`), and the two networks are frozen
# into the fixture as edge lists. Nothing is re-simulated in Julia.

suppressMessages({
  .libPaths(c(path.expand("~/R/library"), .libPaths()))
  library(network)
  library(ergm.multi)
})

seed <- 20260713
set.seed(seed)

n <- 20
grp <- rep(c("a", "b"), length.out = n)
same <- outer(grp, grp, "==")
diag(same) <- FALSE
logistic <- function(x) 1 / (1 + exp(-x))

gen <- list(c(-1.5, 0.9), c(-2.0, 0.4))   # (edges, nodematch) per layer
mk <- function(th) {
  P <- logistic(th[1] + th[2] * same)
  A <- matrix(rbinom(n * n, 1, P), n, n)
  diag(A) <- 0
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- grp
  nw
}
nets <- lapply(gen, mk)
mats <- lapply(nets, function(nw) as.matrix(nw))

offset_coef <- c(0.75, 0.40)

quiet <- function(expr) {
  out <- NULL
  invisible(capture.output(out <- eval.parent(substitute(expr)), type = "output"))
  out
}

# --- (a) the free fit: 4 parameters, dyad-independent, exact MPLE = MLE ------
fit <- quiet(ergm(Networks(nets) ~ N(~edges + nodematch("grp"),
                                     ~factor(.NetworkID) - 1)))
free_coef <- coef(fit)
free_se <- sqrt(diag(vcov(fit)))

# --- (b) the offset fit: nodematch pinned, edges free ------------------------
fit_off <- quiet(ergm(Networks(nets) ~ N(~edges, ~factor(.NetworkID) - 1) +
                        offset(N(~nodematch("grp"), ~factor(.NetworkID) - 1)),
                      offset.coef = offset_coef))
off_all <- coef(fit_off)
# ergm orders the free terms first, then the offset ones.
off_free_coef <- as.numeric(off_all[1:2])
off_free_se <- sqrt(diag(vcov(fit_off)))[1:2]

# --- (c) the null comparison: NO nodematch at all ----------------------------
# If ERGMMulti.jl silently dropped the offsets from the linear predictor, its
# offset fit would land HERE instead. Frozen so the Julia testset can assert it
# does not.
fit_null <- quiet(ergm(Networks(nets) ~ N(~edges, ~factor(.NetworkID) - 1)))
null_coef <- as.numeric(coef(fit_null))

# --- the same estimators, taken to convergence -------------------------------
# ergm's MPLE runs R's `glm` at its default epsilon = 1e-8 and stops there. On the
# sibling TERGM fixture that slack turned out to dominate the entire
# Julia-vs-R disagreement, so it is measured here rather than assumed away: the
# model is dyad-independent and separates by layer, so the exact MLE is two
# ordinary logistic regressions, and they are refit at epsilon = 1e-14.
exact_fit <- function(mat, ctrl) {
  off <- which(row(mat) != col(mat))
  X <- cbind(1, as.numeric(same[off]))
  y <- as.numeric(mat[off])
  g <- glm.fit(X, y, family = binomial(), control = ctrl)
  se <- sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE])))
  list(coef = g$coefficients, se = se)
}
tight <- glm.control(epsilon = 1e-14, maxit = 200)
ex <- lapply(mats, exact_fit, ctrl = tight)
# ergm's coefficient order is (edges L1, edges L2, nodematch L1, nodematch L2).
exact_coef <- c(ex[[1]]$coef[1], ex[[2]]$coef[1], ex[[1]]$coef[2], ex[[2]]$coef[2])
exact_se <- c(ex[[1]]$se[1], ex[[2]]$se[1], ex[[1]]$se[2], ex[[2]]$se[2])
mple_vs_exact_coef <- max(abs(as.numeric(free_coef) - exact_coef))
mple_vs_exact_se <- max(abs(as.numeric(free_se) - exact_se))

# The exact offset fit: nodematch pinned, so its contribution is a fixed additive
# term in the linear predictor and the edges coefficient is the only free one.
exact_offset_fit <- function(mat, oc, ctrl) {
  off <- which(row(mat) != col(mat))
  X <- matrix(1, length(off), 1)
  y <- as.numeric(mat[off])
  os <- oc * as.numeric(same[off])
  g <- glm.fit(X, y, family = binomial(), offset = os, control = ctrl)
  as.numeric(g$coefficients)
}
exact_off_coef <- c(exact_offset_fit(mats[[1]], offset_coef[1], tight),
                    exact_offset_fit(mats[[2]], offset_coef[2], tight))

num <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
strs <- function(x) paste(sprintf('"%s"', x), collapse = ", ")
elist <- function(sel) paste(sapply(mats, function(A) {
  e <- which(A == 1, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")

cat('name = "twolayer_ergm_multi"\n\n')

cat("[provenance]\n")
cat(sprintf('r_version = "%s"\n', as.character(getRversion())))
cat(sprintf('ergm_multi_version = "%s"\n', as.character(packageVersion("ergm.multi"))))
cat(sprintf('ergm_version = "%s"\n', as.character(packageVersion("ergm"))))
cat(sprintf('network_version = "%s"\n', as.character(packageVersion("network"))))
cat(sprintf("seed = %d\n", seed))
cat('script = "test/fixtures/r/twolayer_ergm_multi.R"\n')
cat(sprintf('date = "%s"\n', format(Sys.Date())))
cat('dataset = "simulated: 2 directed layers on the same 20 actors, alternating two-group `grp`; drawn from the dyad-independent model in [values].generating_* -- the layers themselves are frozen below"\n')
cat('model_free = "Networks(list(net1,net2)) ~ N(~edges + nodematch(\\"grp\\"), ~factor(.NetworkID) - 1) -- per-layer edges and nodematch, DYAD-INDEPENDENT so ergm fits it by MPLE = exact MLE"\n')
cat('model_offset = "~ N(~edges, ~factor(.NetworkID) - 1) + offset(N(~nodematch(\\"grp\\"), ~factor(.NetworkID) - 1)), offset.coef = (0.75, 0.40)"\n')
cat('exact_estimator = "the same two logistic regressions refit with glm at epsilon = 1e-14, since ergm stops its MPLE glm at the default 1e-8"\n')
cat("\n")

cat("[tolerance]\n")
cat("# Every term here is DYAD-INDEPENDENT, so the likelihood factorizes over the\n")
cat("# (layer, i, j) dyads: ergm's MPLE is the exact MLE and ERGMMulti.jl's MPLE is\n")
cat("# the same exact MLE. There is no Monte Carlo on either side and nothing to\n")
cat("# average over. The only difference two correct implementations can have is\n")
cat("# where their optimizers stop.\n")
cat("#\n")
cat("# `exact_*` below is the same estimator taken to convergence (glm at\n")
cat("# epsilon = 1e-14 rather than ergm's default 1e-8), and THAT is the assertion\n")
cat("# with teeth: 1e-6, which is ~1e-5 of the smallest standard error in the\n")
cat("# model. If it fails, the (layer, i, j) dyad universe or a change statistic is\n")
cat("# wrong. DO NOT LOOSEN IT.\n")
cat("exact_coefficients = 1e-6\n")
cat("exact_std_errors = 1e-6\n")
cat("exact_offset_coefficients = 1e-6\n")
cat("#\n")
cat("# Against ergm.multi AS SHIPPED the tolerance must also absorb ergm's own\n")
cat("# glm slack, which `mple_vs_exact_*` in [values] measures. It is small here\n")
cat("# (unlike the sibling TERGM fixture, where it dominated), but it is measured\n")
cat("# rather than assumed, and the tolerance is set from the measurement.\n")
cat(sprintf("coefficients = %.1g\n", max(1e-6, 10^ceiling(log10(20 * max(mple_vs_exact_coef, 1e-12))))))
cat(sprintf("std_errors = %.1g\n", max(1e-6, 10^ceiling(log10(20 * max(mple_vs_exact_se, 1e-12))))))
cat(sprintf("offset_coefficients = %.1g\n", max(1e-6, 10^ceiling(log10(20 * max(mple_vs_exact_coef, 1e-12))))))
cat("\n")

cat("[values]\n")
cat("# --- the two layers, frozen. Julia rebuilds them exactly. ---------------\n")
cat(sprintf("n_actors = %d\n", n))
cat("n_layers = 2\n")
cat("directed = true\n")
cat(sprintf("grp = [%s]\n", strs(grp)))
cat(sprintf("edge_counts = [%s]\n", paste(sapply(mats, sum), collapse = ", ")))
cat(sprintf("layer_src = [%s]\n", elist(1)))
cat(sprintf("layer_dst = [%s]\n", elist(2)))
cat("\n# What the layers were drawn from. NOT asserted -- the estimator is being\n")
cat("# compared to R, not to truth -- but a sanity anchor.\n")
cat(sprintf("generating_layer1 = [%s]\n", num(gen[[1]])))
cat(sprintf("generating_layer2 = [%s]\n", num(gen[[2]])))
cat("\n# --- (a) the free fit ---------------------------------------------------\n")
cat(sprintf("term_names = [%s]\n", strs(names(free_coef))))
cat(sprintf("coefficients = [%s]\n", num(as.numeric(free_coef))))
cat(sprintf("std_errors = [%s]\n", num(as.numeric(free_se))))
cat("# ...and the same estimator taken to convergence. This is what ERGMMulti.jl\n")
cat("# is actually held to.\n")
cat(sprintf("exact_coefficients = [%s]\n", num(exact_coef)))
cat(sprintf("exact_std_errors = [%s]\n", num(exact_se)))
cat("# How far ergm.multi AS SHIPPED sits from that exact optimum (its glm stops\n")
cat("# at the default epsilon = 1e-8).\n")
cat(sprintf("mple_vs_exact_coef = %.17g\n", mple_vs_exact_coef))
cat(sprintf("mple_vs_exact_se = %.17g\n", mple_vs_exact_se))
cat("\n# --- (b) the OFFSET fit: nodematch pinned, edges free -------------------\n")
cat(sprintf("offset_values = [%s]\n", num(offset_coef)))
cat('offset_term_names = ["L1.nodematch.grp", "L2.nodematch.grp"]\n')
cat('offset_free_term_names = ["L.edges.1", "L.edges.2"]\n')
cat(sprintf("offset_coefficients = [%s]\n", num(off_free_coef)))
cat(sprintf("offset_std_errors = [%s]\n", num(as.numeric(off_free_se))))
cat(sprintf("exact_offset_coefficients = [%s]\n", num(exact_off_coef)))
cat("\n# --- (c) the NULL comparison: the same model with NO nodematch at all ---\n")
cat("# This is where a fit lands if the offsets are dropped from the linear\n")
cat("# predictor instead of merely from the parameter vector -- the exact bug an\n")
cat("# offset test is for. The Julia testset asserts its offset fit is NOT this,\n")
cat("# so a test that passed by doing nothing on both sides cannot pass here.\n")
cat(sprintf("no_nodematch_coefficients = [%s]\n", num(null_coef)))
